config/routes.rb
Testapp1::Application.routes.draw do
  devise_for :users

    root :to => 'staticpage#index'
    resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  attr_accessible :hour, :emotion, :learned, :image

	mount_uploader :image, ImageUploader

	belongs_to :user
	# user is singular because there is just one user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :pics
  # pics is plural because one user can have many pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	before_filter :authenticate_user!, :only => [:new, :create]
	#requires authenticated user for new and create
	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = current_user.pics.create(params[:pic])
		redirect_to pics_path
	end
	#action above is what happens when the user hits "Submit"
end

app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController

	def index
	end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpage_helper.rb
module StaticpageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to 'Firehose', root_path, :class => 'brand' %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      	<ul class="nav">
      		<li>
      		<%= link_to 'My App', pics_path %>
    		  </li>  	
      	   <li>
            <%= link_to 'New Pic', new_pic_path %>
            </li>   
      </ul>

     <ul class="nav pull-right">
        
        <% if user_signed_in? %>

            <li>

              <%= link_to current_user.email, '#' %>
            </li>               

            <li>

              <%= link_to 'Sign Out', destroy_user_session_path, :method => 'delete' %>
            </li>   
        
        <% else %>

            <li>
              <%= link_to 'Sign Up', new_user_registration_path %>
            </li>   


           <li>
             <%= link_to 'Sign In', new_user_session_path %>
            </li>        
        
          <% end %>

          </ul>



      </div>
 
    </div>
  </div>
</div>




<% if notice.present? %>
  <p class="notice"><%= notice %></p>
<% end %>

<% if alert.present? %>
  <p class="alert"><%= alert %></p>
<% end %>



<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<div class="custom-font">

<h2 class="cool-font-big text-center">My Coding Journey</h2>

	<div class="container">
		<div class="row">

			<% @pics.each do |pic| %>
				<div class="boxy span3">
					<h2>
						Hour <%= pic.hour %>	
					</h2>

					<div>
						<%= image_tag pic.image.to_s %>
					</div>

					<p>
						<%= pic.emotion %>
					</p>	
				
					<p>
						I learned
						<%= pic.learned %>
					</p>	
			
					<% if pic.user.present? %>
					<p>
						<b>Email:</b> <%= pic.user.email %>
					</p>	
					<% end %>


				</div>
			<% end %>


		</div>
	</div>
</div>

app/views/pics/new.html.erb
<div class="custom-font span6 offset3 text-center boxy">

	<h2 class="cool-font-small">Upload Your Stuff</h2>

	<%= simple_form_for @pic do |f| %>
		<%= f.input :hour, label: 'Which Hour?', placeholder: 'Enter the hour'	 %>
		<%= f.input :image, :as => :file %>
		
		<%= f.input :emotion, label: 'How did you feel?', placeholder: 'Happy, Stoked, Awesome,...' %>
		<%= f.input :learned, label: 'What did you learn?', placeholder: 'Installation, CSS, html, ruby,...', :input_html => {rows: '3'} %>

		<br/>
		<%= link_to 'Cancel', pics_path, :class=> 'btn btn-danger btn-large' %>

		<%=submit_tag 'Submit', :class=> 'btn btn-danger btn-large' %>


	<% end %>	

</div>

app/views/staticpage/index.html.erb
<div class="custom-font boxy span6 offset3 text-center">

	<h1 class="cool-font-big">Hi I'm Gladys</h1>

		<br/>

		<h2 class="cool-font-small">I'm having a lot of fun learning how to code! Yay!</h2>

	<br/>

		<%= link_to 'Launch', pics_path, :class=> 'btn btn-danger btn-large' %>

</div>	